package com.skripsi.lostfoundstis

@Suppress("PropertyName")
class Configuration {
    // Dibawah ini merupakan pengalamatan dimana lokasi skrip CRUD PHP disimpan
    val URL_MAIN         = "http://192.168.43.130/LostFound/"
    val URL_USER_LOGIN   = "http://192.168.43.130/LostFound/PHP/Login.php"

    val URL_ADD_CARI     = "http://192.168.43.130/LostFound/PHP/TambahPencarian.php"
    val URL_ADD_TEMU     = "http://192.168.43.130/LostFound/PHP/TambahPenemuan.php"
    val URL_GET_ALL_CARI = "http://192.168.43.130/LostFound/PHP/TampilSemuaPencarian.php"
    val URL_GET_ALL_TEMU = "http://192.168.43.130/LostFound/PHP/TampilSemuaPenemuan.php"
    val URL_GET_ONE_CARI = "http://192.168.43.130/LostFound/PHP/DetailPencarian.php?id_cari="
    val URL_GET_ONE_TEMU = "http://192.168.43.130/LostFound/PHP/DetailPenemuan.php?id_temu="
    val URL_UPDATE_CARI  = "http://192.168.43.130/LostFound/PHP/UpdatePencarian.php"
    val URL_UPDATE_TEMU  = "http://192.168.43.130/LostFound/PHP/UpdatePenemuan.php"
    val URL_DELETE_CARI  = "http://192.168.43.130/LostFound/PHP/HapusPencarian.php?id_cari="
    val URL_DELETE_TEMU  = "http://192.168.43.130/LostFound/PHP/HapusPenemuan.php?id_cari="
    val URL_FINISH_CARI  = "http://192.168.43.130/LostFound/PHP/SelesaiPencarian.php?id_cari="
    val URL_FINISH_TEMU  = "http://192.168.43.130/LostFound/PHP/SelesaiPenemuan.php?id_cari="

    val URL_IMG_LOC      = "http://192.168.43.130/LostFound/img/"
    val URL_IMG_LOC_CARI = "http://192.168.43.130/LostFound/img/cari/"
    val URL_IMG_LOC_TEMU = "http://192.168.43.130/LostFound/img/temu/"

    val URL_GET_ALL_SAYA = "http://192.168.43.130/LostFound/PHP/MyPencarian.php?id_pencari="

    val URL_GET_PROFIL   = "http://192.168.43.130/LostFound/PHP/MyProfil.php?id_user="
    val TAG_PROFIL_JSON  = "result_profil"
    val TAG_NAMA_USER    = "nama_user"
    val TAG_STS_USER     = "sts_user"
    val TAG_JK_USER      = "jk_user"
    val TAG_EMAIL_USER   = "email_user"
    val TAG_PHONE_USER   = "phone_user"

    val URL_GET_JBAR     = "http://192.168.43.130/LostFound/PHP/DaftarJenisBarang.php"
    val TAG_JBAR_JSON    = "result_jbar"
    val TAG_ID_JBAR      = "id_jbar"
    val TAG_KEL_BAR      = "kel_bar"
    val TAG_KAT_BAR      = "kat_bar"

    val URL_GET_LOK      = "http://192.168.43.130/LostFound/PHP/DaftarLokasiKampus.php"
    val TAG_LOK_JSON     = "result_lok"
    val TAG_ID_LOK       = "id_lok"
    val TAG_GD_LOK       = "gd_lok"
    val TAG_RG_LOK       = "rg_lok"

    // Dibawah ini merupakan kunci untuk pencarian yang akan digunakan untuk mengirim permintaan ke Skrip PHP
    val KEY_CARI_ID      = "id_cari"
    val KEY_CARI_ID_JBAR = "id_jbar_cari"
    val KEY_CARI_JBAR    = "jbar_cari"
    val KEY_CARI_ID_LOK  = "id_lok_cari"
    val KEY_CARI_LOK     = "lok_cari"
    val KEY_CARI_JDL     = "jdl_cari"
    val KEY_CARI_CIRI    = "cir_bar_cari"
    val KEY_CARI_KEL     = "kel_bar_cari"
    val KEY_CARI_KAT     = "kat_bar_cari"
    val KEY_CARI_GD      = "gd_kps_cari"
    val KEY_CARI_RG      = "rg_kps_cari"
    val KEY_CARI_WKT     = "wkt_cari"
    val KEY_CARI_WKTB    = "wkt_buat_cari"
    val KEY_CARI_STS     = "sts_cari"
    val KEY_CARI_FOTO    = "fot_bar_cari"

    val TAG_CARI_JSON_ARRAY = "result_cari"
    val TAG_CARI_ID      = "id_cari"
    val TAG_CARI_ID_JBAR = "id_jbar_cari"
    val TAG_CARI_JBAR    = "jbar_cari"
    val TAG_CARI_ID_LOK  = "id_lok_cari"
    val TAG_CARI_LOK     = "lok_cari"
    val TAG_CARI_JDL     = "jdl_cari"
    val TAG_CARI_CIRI    = "cir_bar_cari"
    val TAG_CARI_KEL     = "kel_bar_cari"
    val TAG_CARI_KAT     = "kat_bar_cari"
    val TAG_CARI_GD      = "gd_kps_cari"
    val TAG_CARI_RG      = "rg_kps_cari"
    val TAG_CARI_WKT     = "wkt_cari"
    val TAG_CARI_TGL     = "tgl_cari"
    val TAG_CARI_FOTO    = "fot_bar_cari"

    val CARI_ID          = "id_cari"

    // Dibawah ini merupakan kunci untuk penemuan yang akan digunakan untuk mengirim permintaan ke Skrip PHP
    val KEY_TEMU_ID      = "id_temu"
    val KEY_TEMU_ID_JBAR = "id_jbar_temu"
    val KEY_TEMU_JBAR    = "jbar_temu"
    val KEY_TEMU_ID_LOK  = "id_lok_temu"
    val KEY_TEMU_LOK     = "lok_temu"
    val KEY_TEMU_JDL     = "jdl_temu"
    val KEY_TEMU_CIRI    = "cir_bar_temu"
    val KEY_TEMU_KEL     = "kel_bar_temu"
    val KEY_TEMU_KAT     = "kat_bar_temu"
    val KEY_TEMU_GD      = "gd_kps_temu"
    val KEY_TEMU_RG      = "rg_kps_temu"
    val KEY_TEMU_WKT     = "wkt_temu"
    val KEY_TEMU_WKTB    = "wkt_buat_temu"
    val KEY_TEMU_STS     = "sts_temu"
    val KEY_TEMU_FOTO    = "fot_bar_temu"

    val TAG_TEMU_JSON_ARRAY = "result_temu"
    val TAG_TEMU_ID      = "id_temu"
    val TAG_TEMU_ID_JBAR = "id_jbar_temu"
    val TAG_TEMU_JBAR    = "jbar_temu"
    val TAG_TEMU_ID_LOK  = "id_lok_temu"
    val TAG_TEMU_LOK     = "lok_temu"
    val TAG_TEMU_JDL     = "jdl_temu"
    val TAG_TEMU_CIRI    = "cir_bar_temu"
    val TAG_TEMU_KEL     = "kel_bar_temu"
    val TAG_TEMU_KAT     = "kat_bar_temu"
    val TAG_TEMU_GD      = "gd_kps_temu"
    val TAG_TEMU_RG      = "rg_kps_temu"
    val TAG_TEMU_WKT     = "wkt_temu"
    val TAG_TEMU_TGL     = "tgl_temu"
    val TAG_TEMU_FOTO    = "fot_bar_temu"

    val TEMU_ID          = "id_temu"
}